name: Nightly (Jahia Release)

on:
  workflow_dispatch:
  schedule:
    - cron:  '0 0 * * *'

jobs:
  integration-tests-standalone:
    name: Integration Tests (Standalone - Release)
#    uses: Jahia/jahia-modules-action/.github/workflows/reusable-integration-tests.yml@v2
    uses: Jahia/jahia-modules-action/.github/workflows/reusable-integration-tests.yml@support-custom-docker-compose-file-BACKUP-with-temp-change
    secrets: inherit
    with:
      jahia_image: jahia/jahia-ee:8.1
      module_id: sitemap
      testrail_project: Sitemap Module
      pagerduty_incident_service: sitemap-JahiaRL
      provisioning_manifest: provisioning-manifest-release-8.1.x.yml
      artifact_prefix: sitemap-standalone-rl
      module_branch: ${{ github.ref }}
